version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 20
    ignore:
      # All of these dependencies require Node v16 or greater
      - dependency-name: "@types/node"
        versions: [">=15"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: [">=6"]
      - dependency-name: "@typescript-eslint/parser"
        versions: [">=6"]
      - dependency-name: "@typescript-eslint/utils"
        versions: [">=6"]
      - dependency-name: "eslint-plugin-deprecation"
        versions: [">=2"]
      - dependency-name: "discord.js"
        versions: [">=13"]
      - dependency-name: "glob"
        versions: [">=9"]
      - dependency-name: "puppeteer"
      - dependency-name: "mediasoup"
        versions: [">=3.13.0"]
      - dependency-name: "@testing-library/react"
        versions: [">=15"]
      # marked has had significant API revisions that we need to take manually
      - dependency-name: "marked"
        versions: [">=5"]
      - dependency-name: "@types/marked"
        versions: [">=5"]
    groups:
      aws:
        patterns:
          - "@aws-sdk/*"
      google:
        patterns:
          - "@googleapis/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
